global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "example_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any metrics scraped from this config.
  - job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ['localhost:9090']

  # Social Media Analytics Platform metrics
  - job_name: 'social-media-analytics'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:8000']  # FastAPI metrics endpoint
    metrics_path: '/metrics'
    
  # Kafka metrics
  - job_name: 'kafka'
    scrape_interval: 30s
    static_configs:
      - targets: ['kafka:9101']  # Kafka JMX exporter
    metrics_path: '/metrics'
    
  # PostgreSQL metrics (if using postgres_exporter)
  - job_name: 'postgres'
    scrape_interval: 30s
    static_configs:
      - targets: ['postgres:9187']  # postgres_exporter default port
    metrics_path: '/metrics'
    
  # Redis metrics (if using redis_exporter)
  - job_name: 'redis'
    scrape_interval: 30s
    static_configs:
      - targets: ['redis:9121']  # redis_exporter default port
    metrics_path: '/metrics'
    
  # MinIO metrics
  - job_name: 'minio'
    scrape_interval: 30s
    static_configs:
      - targets: ['minio:9000']
    metrics_path: '/minio/v2/metrics/cluster'
    
  # Node exporter for system metrics
  - job_name: 'node'
    scrape_interval: 30s
    static_configs:
      - targets: ['localhost:9100']  # node_exporter default port
    metrics_path: '/metrics'
